# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voice-recognition2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread
from PyQt5.QtWidgets import QFileDialog

from VoiceVerificator import VoiceVerificator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.init_training_thread()
        self.init_verification_thread()
        self.init_file_verification_thread()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 600, 330))
        self.stackedWidget.setObjectName("stackedWidget")
        self.menuPage = QtWidgets.QWidget()
        self.menuPage.setObjectName("menuPage")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menuPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 150, 219, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newProfileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.newProfileButton.setObjectName("newProfileButton")
        self.verticalLayout.addWidget(self.newProfileButton)
        self.verifyButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.verifyButton.setObjectName("verifyButton")
        self.verticalLayout.addWidget(self.verifyButton)
        self.menuLabel = QtWidgets.QLabel(self.menuPage)
        self.menuLabel.setEnabled(True)
        self.menuLabel.setGeometry(QtCore.QRect(30, 0, 541, 61))
        self.menuLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.menuLabel.setFont(font)
        self.menuLabel.setTextFormat(QtCore.Qt.AutoText)
        self.menuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.menuLabel.setObjectName("menuLabel")
        self.stackedWidget.addWidget(self.menuPage)
        # self.stackedWidget.setCurrentWidget(self.menuPage)
        self.newProfilePage = QtWidgets.QWidget()
        self.newProfilePage.setObjectName("newProfilePage")
        self.newProfileLabel = QtWidgets.QLabel(self.newProfilePage)
        self.newProfileLabel.setEnabled(True)
        self.newProfileLabel.setGeometry(QtCore.QRect(30, 0, 541, 61))
        self.newProfileLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.newProfileLabel.setFont(font)
        self.newProfileLabel.setTextFormat(QtCore.Qt.AutoText)
        self.newProfileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newProfileLabel.setObjectName("newProfileLabel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.newProfilePage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 170, 258, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newProfileNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.newProfileNameLabel.setObjectName("newProfileNameLabel")
        self.verticalLayout_2.addWidget(self.newProfileNameLabel)
        self.newProfileNameInput = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.newProfileNameInput.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newProfileNameInput.sizePolicy().hasHeightForWidth())
        self.newProfileNameInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newProfileNameInput.setFont(font)
        self.newProfileNameInput.setObjectName("newProfileNameInput")
        self.verticalLayout_2.addWidget(self.newProfileNameInput)
        self.statusLabelNP = QtWidgets.QLabel(self.newProfilePage)
        self.statusLabelNP.setGeometry(QtCore.QRect(220, 250, 161, 16))
        self.statusLabelNP.setStyleSheet("background-color: red")
        self.statusLabelNP.setText("")
        self.statusLabelNP.setObjectName("statusLabelNP")
        self.startRecordingButton = QtWidgets.QPushButton(self.newProfilePage)
        self.startRecordingButton.setGeometry(QtCore.QRect(220, 270, 161, 24))
        self.startRecordingButton.setObjectName("startRecordingButton")
        self.backButtonNP = QtWidgets.QPushButton(self.newProfilePage)
        self.backButtonNP.setGeometry(QtCore.QRect(20, 270, 75, 24))
        self.backButtonNP.setObjectName("backButtonNP")
        self.label_1NP = QtWidgets.QLabel(self.newProfilePage)
        self.label_1NP.setGeometry(QtCore.QRect(20, 80, 351, 21))
        self.label_1NP.setObjectName("label_1NP")
        self.label_2NP = QtWidgets.QLabel(self.newProfilePage)
        self.label_2NP.setGeometry(QtCore.QRect(20, 120, 561, 21))
        self.label_2NP.setObjectName("label_2NP")
        self.microphoneSelectNP = QtWidgets.QComboBox(self.newProfilePage)
        self.microphoneSelectNP.setGeometry(QtCore.QRect(320, 210, 261, 22))
        self.microphoneSelectNP.setObjectName("microphoneSelectNP")
        self.label_3NP = QtWidgets.QLabel(self.newProfilePage)
        self.label_3NP.setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.label_3NP.setObjectName("label_3NP")
        self.stackedWidget.addWidget(self.newProfilePage)
        self.profileListPage = QtWidgets.QWidget()
        self.profileListPage.setObjectName("profileListPage")
        self.profileListLabel = QtWidgets.QLabel(self.profileListPage)
        self.profileListLabel.setEnabled(True)
        self.profileListLabel.setGeometry(QtCore.QRect(280, 60, 241, 91))
        self.profileListLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.profileListLabel.setFont(font)
        self.profileListLabel.setTextFormat(QtCore.Qt.AutoText)
        self.profileListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.profileListLabel.setObjectName("profileListLabel")
        self.profileList = QtWidgets.QListView(self.profileListPage)
        self.profileList.setGeometry(QtCore.QRect(270, 200, 256, 192))
        self.profileList.setObjectName("profileList")
        self.stackedWidget.addWidget(self.profileListPage)
        self.verificationPage = QtWidgets.QWidget()
        self.verificationPage.setObjectName("verificationPage")
        self.verificationLabel = QtWidgets.QLabel(self.verificationPage)
        self.verificationLabel.setEnabled(True)
        self.verificationLabel.setGeometry(QtCore.QRect(30, 0, 541, 61))
        self.verificationLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.verificationLabel.setFont(font)
        self.verificationLabel.setTextFormat(QtCore.Qt.AutoText)
        self.verificationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.verificationLabel.setObjectName("verificationLabel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.verificationPage)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 170, 258, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.profileNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.profileNameLabel.setObjectName("profileNameLabel")
        self.verticalLayout_3.addWidget(self.profileNameLabel)
        self.profileNameInput = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.profileNameInput.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileNameInput.sizePolicy().hasHeightForWidth())
        self.profileNameInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.profileNameInput.setFont(font)
        self.profileNameInput.setObjectName("profileNameInput")
        self.verticalLayout_3.addWidget(self.profileNameInput)
        self.statusLabelVP = QtWidgets.QLabel(self.verificationPage)
        self.statusLabelVP.setGeometry(QtCore.QRect(220, 250, 161, 16))
        self.statusLabelVP.setStyleSheet("background-color: red")
        self.statusLabelVP.setText("")
        self.statusLabelVP.setObjectName("statusLabelVP")
        self.startVerificationButton = QtWidgets.QPushButton(self.verificationPage)
        self.startVerificationButton.setGeometry(QtCore.QRect(220, 270, 161, 24))
        self.startVerificationButton.setObjectName("startVerificationButton")
        self.backButtonVP = QtWidgets.QPushButton(self.verificationPage)
        self.backButtonVP.setGeometry(QtCore.QRect(20, 270, 75, 24))
        self.backButtonVP.setObjectName("backButtonVP")
        self.startFileVerificationButton = QtWidgets.QPushButton(self.verificationPage)
        self.startFileVerificationButton.setGeometry(QtCore.QRect(110, 270, 93, 24))
        self.startFileVerificationButton.setObjectName("startFileVerificationButton")
        self.label_1VP = QtWidgets.QLabel(self.verificationPage)
        self.label_1VP.setGeometry(QtCore.QRect(20, 80, 561, 21))
        self.label_1VP.setObjectName("label_1VP")
        self.label_2VP = QtWidgets.QLabel(self.verificationPage)
        self.label_2VP.setGeometry(QtCore.QRect(20, 120, 561, 21))
        self.label_2VP.setObjectName("label_2VP")
        self.label_3VP = QtWidgets.QLabel(self.verificationPage)
        self.label_3VP.setGeometry(QtCore.QRect(20, 100, 351, 21))
        self.label_3VP.setObjectName("label_3VP")
        self.resultLabel = QtWidgets.QLabel(self.verificationPage)
        self.resultLabel.setGeometry(QtCore.QRect(420, 269, 151, 21))
        self.resultLabel.setObjectName("resultLabel")
        self.microphoneSelectVP = QtWidgets.QComboBox(self.verificationPage)
        self.microphoneSelectVP.setGeometry(QtCore.QRect(320, 210, 261, 22))
        self.microphoneSelectVP.setObjectName("microphoneSelectVP")
        self.stackedWidget.addWidget(self.verificationPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.microphoneSelectNP.addItems(self.voice_verificator.get_input_device_list())
        self.microphoneSelectVP.addItems(self.training_voice_verificator.get_input_device_list())
        self.microphoneSelectNP.activated.connect(self.microphone_select_activated)

        self.startRecordingButton.setDisabled(True)
        self.startVerificationButton.setDisabled(True)
        self.startFileVerificationButton.setDisabled(True)
        self.startRecordingButton.clicked.connect(self.start_new_profile_recording)
        self.startVerificationButton.clicked.connect(self.start_verification)

        self.profileNameInput.textChanged.connect(self.on_profile_name_input_value_change)
        self.newProfileNameInput.textChanged.connect(self.on_new_profile_name_input_value_change)

        self.backButtonNP.clicked.connect(self.go_to_menu)
        self.backButtonVP.clicked.connect(self.go_to_menu)
        self.newProfileButton.clicked.connect(self.go_to_new_profile)
        self.verifyButton.clicked.connect(self.go_to_verification)
        self.startFileVerificationButton.clicked.connect(self.open_file_dialog)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def go_to_menu(self):
        self.newProfileNameInput.setText('')
        self.profileNameInput.setText('')
        self.startVerificationButton.setDisabled(True)
        self.startRecordingButton.setDisabled(True)
        self.stackedWidget.setCurrentWidget(self.menuPage)
        self.resultLabel.setText('')

    def go_to_new_profile(self):
        self.stackedWidget.setCurrentWidget(self.newProfilePage)

    def go_to_verification(self):
        self.stackedWidget.setCurrentWidget(self.verificationPage)

    def start_new_profile_recording(self):
        self.startRecordingButton.setDisabled(True)
        self.backButtonNP.setDisabled(True)
        self.training_thread.start()

    def start_verification(self):
        self.startVerificationButton.setDisabled(True)
        self.backButtonVP.setDisabled(True)
        self.verification_thread.start()

    def on_profile_name_input_value_change(self):
        if len(self.profileNameInput.toPlainText()) != 0:
            self.startVerificationButton.setEnabled(True)
            self.startFileVerificationButton.setEnabled(True)
        else:
            self.startVerificationButton.setDisabled(True)
            self.startFileVerificationButton.setDisabled(True)
        self.voice_verificator.username = self.profileNameInput.toPlainText()
        self.file_voice_verificator.username = self.profileNameInput.toPlainText()
        # print(self.voice_verificator.username)

    def on_new_profile_name_input_value_change(self):
        if len(self.newProfileNameInput.toPlainText()) != 0:
            self.startRecordingButton.setEnabled(True)
        else:
            self.startRecordingButton.setDisabled(True)
        self.training_voice_verificator.username = self.newProfileNameInput.toPlainText()
        # print(self.training_voice_verificator.username)

    def microphone_select_activated(self, index):
        self.voice_verificator.input_device_index = index
        self.training_voice_verificator.input_device_index = index
        print(self.voice_verificator.input_device_index)

    def on_training_recording_value_changed(self, value):
        if value:
            self.statusLabelNP.setStyleSheet('background-color: green')
        else:
            self.statusLabelNP.setStyleSheet('background-color: red')

    def on_training_recording_finished(self):
        self.startRecordingButton.setEnabled(True)
        self.backButtonNP.setEnabled(True)

    def init_training_thread(self):
        self.training_thread = QThread()
        self.training_voice_verificator = VoiceVerificator()

        self.training_voice_verificator.moveToThread(self.training_thread)
        self.training_voice_verificator.finished.connect(self.training_thread.quit)
        self.training_voice_verificator.is_recording.connect(self.on_training_recording_value_changed)

        self.training_thread.started.connect(self.training_voice_verificator.record_audio_train)
        self.training_thread.finished.connect(self.on_training_recording_finished)

        # self.voice_verificator.finished.connect(self.voice_verificator.deleteLater)
        # self.training_thread.finished.connect(self.training_thread.deleteLater)

    def on_verification_recording_value_changed(self, value):
        if value:
            self.statusLabelVP.setStyleSheet('background-color: green')
        else:
            self.statusLabelVP.setStyleSheet('background-color: red')

    def on_verification_recording_finished(self):
        self.startVerificationButton.setEnabled(True)
        self.backButtonVP.setEnabled(True)

    def init_verification_thread(self):
        self.verification_thread = QThread()
        self.voice_verificator = VoiceVerificator()

        self.voice_verificator.moveToThread(self.verification_thread)
        self.voice_verificator.finished.connect(self.verification_thread.quit)
        self.voice_verificator.is_recording.connect(self.on_verification_recording_value_changed)
        self.voice_verificator.result.connect(self.set_result)

        self.verification_thread.started.connect(self.voice_verificator.record_audio_test)
        self.verification_thread.finished.connect(self.on_verification_recording_finished)

        # self.voice_verificator.finished.connect(self.voice_verificator.deleteLater)
        # self.training_thread.finished.connect(self.training_thread.deleteLater)

    def set_result(self, result):
        self.resultLabel.setText(result)

    def init_file_verification_thread(self):
        self.file_verification_thread = QThread()
        self.file_voice_verificator = VoiceVerificator()

        self.file_voice_verificator.moveToThread(self.file_verification_thread)
        self.file_voice_verificator.finished.connect(self.file_verification_thread.quit)
        self.file_voice_verificator.result.connect(self.set_result)
        self.file_verification_thread.started.connect(self.file_voice_verificator.test_file_recording)

    def open_file_dialog(self):
        file_formats = '*.wav'
        filename, _ = QFileDialog.getOpenFileName(parent=None,
                                                  caption='Wybierz plik do weryfikacji',
                                                  directory=os.getcwd() + '/testing_set',
                                                  filter=file_formats)
        if filename is not '':
            print(filename)
            path = filename.split('/')
            print(path[len(path) - 1])
            self.file_voice_verificator.verification_filename = path[len(path) - 1]
            print(self.file_voice_verificator.verification_filename[:-11])
            self.file_verification_thread.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weryfikacja głosowa"))
        self.newProfileButton.setText(_translate("MainWindow", "Nowy profil"))
        self.verifyButton.setText(_translate("MainWindow", "Weryfikacja"))
        self.menuLabel.setText(_translate("MainWindow", "MENU"))
        self.newProfileLabel.setText(_translate("MainWindow", "Nowy Profil"))
        self.newProfileNameLabel.setText(_translate("MainWindow", "Nazwa profilu:"))
        self.startRecordingButton.setText(_translate("MainWindow", "Rozpocznij nagrywanie"))
        self.backButtonNP.setText(_translate("MainWindow", "Cofnij"))
        self.label_1NP.setText(_translate("MainWindow", "Aby moć rozpocząć nagrywanie wpisz nazwę profilu w odpowiednim polu."))
        self.label_2NP.setText(_translate("MainWindow", "Po naciśnięciu przycisku 'Rozpocznij Nagrywanie', 5 razy wypowiedz hasło, gdy ikonka zaświeci się na zielono."))
        self.label_3NP.setText(_translate("MainWindow", "W polu po prawej stronie wybierz odpowiednie urządzenie nagrywające."))
        self.profileListLabel.setText(_translate("MainWindow", "Lista Profili"))
        self.verificationLabel.setText(_translate("MainWindow", "Weryfikacja"))
        self.profileNameLabel.setText(_translate("MainWindow", "Nazwa profilu:"))
        self.startVerificationButton.setText(_translate("MainWindow", "Rozpocznij nagrywanie"))
        self.backButtonVP.setText(_translate("MainWindow", "Cofnij"))
        self.startFileVerificationButton.setText(_translate("MainWindow", "Weryfikuj z pliku"))
        self.label_1VP.setText(_translate("MainWindow", "Aby moć wykonać weryfikacje wpisz nazwę swojego profilu w odpowiednim polu."))
        self.label_2VP.setText(_translate("MainWindow", "Po naciśnięciu przycisku 'Rozpocznij Nagrywanie' wypowiedz hasło, gdy ikonka zaświeci się na zielono."))
        self.label_3VP.setText(_translate("MainWindow", "W polu po prawej stronie wybierz odpowiednie urządzenie nagrywające."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
